name: Build and test

on:
  push:
    branches: [main]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: Build and test
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.build_config}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build
      
      - name: Build Tests
        run: cmake --build ${{github.workspace}}/build --target eai-toolbox-test
    
      - name: Build ASAN Tests
        if: matrix.os != 'windows-latest'
        run: cmake --build ${{github.workspace}}/build --target eai-toolbox-test-asan
    
      - name: Execute Tests on Windows
        if: matrix.os == 'windows-latest'
        run: ${{github.workspace}}\build\${{env.BUILD_TYPE}}\eai-toolbox-test.exe

      - name: Execute ASAN Tests
        if: matrix.os != 'windows-latest'
        run: ${{github.workspace}}/build/eai-toolbox-test-asan
